from PyQt5 import QtCore, QtGui, QtWidgets
import os,time,calendar
from datetime import date

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1142, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1071, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(212, 60, 41, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 60, 28, 16))
        self.label_6.setObjectName("label_6")
        self.a3 = QtWidgets.QComboBox(self.centralwidget)
        self.a3.setGeometry(QtCore.QRect(20, 80, 171, 22))
        self.a3.setObjectName("a3")
        self.a3.addItem("")
        self.a3.setItemText(0, "")
        self.a3.addItem("")
        self.a3.addItem("")
        self.a3.addItem("")
        self.a3.addItem("")
        self.a3.addItem("")
        self.a3.addItem("")
        self.a3.addItem("")
        self.a0 = QtWidgets.QLineEdit(self.centralwidget)
        self.a0.setGeometry(QtCore.QRect(210, 80, 71, 22))
        self.a0.setInputMask("")
        self.a0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.a0.setObjectName("a0")
        self.a1 = QtWidgets.QLineEdit(self.centralwidget)
        self.a1.setGeometry(QtCore.QRect(300, 80, 81, 22))
        self.a1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.a1.setObjectName("a1")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.label_10.setObjectName("label_10")
        self.a2 = QtWidgets.QLineEdit(self.centralwidget)
        self.a2.setGeometry(QtCore.QRect(400, 80, 81, 22))
        self.a2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.a2.setObjectName("a2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(930, 60, 55, 16))
        self.label_11.setObjectName("label_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(830, 60, 28, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(740, 60, 33, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 60, 26, 16))
        self.label_9.setObjectName("label_9")
        self.q1 = QtWidgets.QLineEdit(self.centralwidget)
        self.q1.setGeometry(QtCore.QRect(830, 80, 81, 22))
        self.q1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.q1.setObjectName("q1")
        self.q2 = QtWidgets.QLineEdit(self.centralwidget)
        self.q2.setGeometry(QtCore.QRect(930, 80, 81, 22))
        self.q2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.q2.setObjectName("q2")
        self.q3 = QtWidgets.QComboBox(self.centralwidget)
        self.q3.setGeometry(QtCore.QRect(550, 80, 171, 22))
        self.q3.setObjectName("q3")
        self.q3.addItem("")
        self.q3.setItemText(0, "")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q0 = QtWidgets.QLineEdit(self.centralwidget)
        self.q0.setGeometry(QtCore.QRect(740, 80, 71, 22))
        self.q0.setInputMask("")
        self.q0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.q0.setObjectName("q0")
        self.b1 = QtWidgets.QLineEdit(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(300, 110, 81, 22))
        self.b1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1.setObjectName("b1")
        self.r2 = QtWidgets.QLineEdit(self.centralwidget)
        self.r2.setGeometry(QtCore.QRect(930, 110, 81, 22))
        self.r2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r2.setObjectName("r2")
        self.b2 = QtWidgets.QLineEdit(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(400, 110, 81, 22))
        self.b2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2.setObjectName("b2")
        self.r0 = QtWidgets.QLineEdit(self.centralwidget)
        self.r0.setGeometry(QtCore.QRect(740, 110, 71, 22))
        self.r0.setInputMask("")
        self.r0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r0.setObjectName("r0")
        self.r3 = QtWidgets.QComboBox(self.centralwidget)
        self.r3.setGeometry(QtCore.QRect(550, 110, 171, 22))
        self.r3.setObjectName("r3")
        self.r3.addItem("")
        self.r3.setItemText(0, "")
        self.r3.addItem("")
        self.r3.addItem("")
        self.r3.addItem("")
        self.r3.addItem("")
        self.r3.addItem("")
        self.r3.addItem("")
        self.r3.addItem("")
        self.b3 = QtWidgets.QComboBox(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(20, 110, 171, 22))
        self.b3.setObjectName("b3")
        self.b3.addItem("")
        self.b3.setItemText(0, "")
        self.b3.addItem("")
        self.b3.addItem("")
        self.b3.addItem("")
        self.b3.addItem("")
        self.b3.addItem("")
        self.b3.addItem("")
        self.b3.addItem("")
        self.b0 = QtWidgets.QLineEdit(self.centralwidget)
        self.b0.setGeometry(QtCore.QRect(210, 110, 71, 22))
        self.b0.setInputMask("")
        self.b0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b0.setObjectName("b0")
        self.r1 = QtWidgets.QLineEdit(self.centralwidget)
        self.r1.setGeometry(QtCore.QRect(830, 110, 81, 22))
        self.r1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r1.setObjectName("r1")
        self.c1 = QtWidgets.QLineEdit(self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(300, 140, 81, 22))
        self.c1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.c1.setObjectName("c1")
        self.d2 = QtWidgets.QLineEdit(self.centralwidget)
        self.d2.setGeometry(QtCore.QRect(400, 170, 81, 22))
        self.d2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.d2.setObjectName("d2")
        self.d3 = QtWidgets.QComboBox(self.centralwidget)
        self.d3.setGeometry(QtCore.QRect(20, 170, 171, 22))
        self.d3.setObjectName("d3")
        self.d3.addItem("")
        self.d3.setItemText(0, "")
        self.d3.addItem("")
        self.d3.addItem("")
        self.d3.addItem("")
        self.d3.addItem("")
        self.d3.addItem("")
        self.d3.addItem("")
        self.d3.addItem("")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(930, 170, 81, 22))
        self.t2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2.setObjectName("t2")
        self.s2 = QtWidgets.QLineEdit(self.centralwidget)
        self.s2.setGeometry(QtCore.QRect(930, 140, 81, 22))
        self.s2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2.setObjectName("s2")
        self.c2 = QtWidgets.QLineEdit(self.centralwidget)
        self.c2.setGeometry(QtCore.QRect(400, 140, 81, 22))
        self.c2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.c2.setObjectName("c2")
        self.d0 = QtWidgets.QLineEdit(self.centralwidget)
        self.d0.setGeometry(QtCore.QRect(210, 170, 71, 22))
        self.d0.setInputMask("")
        self.d0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.d0.setObjectName("d0")
        self.s0 = QtWidgets.QLineEdit(self.centralwidget)
        self.s0.setGeometry(QtCore.QRect(740, 140, 71, 22))
        self.s0.setInputMask("")
        self.s0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s0.setObjectName("s0")
        self.s3 = QtWidgets.QComboBox(self.centralwidget)
        self.s3.setGeometry(QtCore.QRect(550, 140, 171, 22))
        self.s3.setObjectName("s3")
        self.s3.addItem("")
        self.s3.setItemText(0, "")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.t3 = QtWidgets.QComboBox(self.centralwidget)
        self.t3.setGeometry(QtCore.QRect(550, 170, 171, 22))
        self.t3.setObjectName("t3")
        self.t3.addItem("")
        self.t3.setItemText(0, "")
        self.t3.addItem("")
        self.t3.addItem("")
        self.t3.addItem("")
        self.t3.addItem("")
        self.t3.addItem("")
        self.t3.addItem("")
        self.t3.addItem("")
        self.c3 = QtWidgets.QComboBox(self.centralwidget)
        self.c3.setGeometry(QtCore.QRect(20, 140, 171, 22))
        self.c3.setObjectName("c3")
        self.c3.addItem("")
        self.c3.setItemText(0, "")
        self.c3.addItem("")
        self.c3.addItem("")
        self.c3.addItem("")
        self.c3.addItem("")
        self.c3.addItem("")
        self.c3.addItem("")
        self.c3.addItem("")
        self.c0 = QtWidgets.QLineEdit(self.centralwidget)
        self.c0.setGeometry(QtCore.QRect(210, 140, 71, 22))
        self.c0.setInputMask("")
        self.c0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.c0.setObjectName("c0")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(830, 170, 81, 22))
        self.t1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t1.setObjectName("t1")
        self.s1 = QtWidgets.QLineEdit(self.centralwidget)
        self.s1.setGeometry(QtCore.QRect(830, 140, 81, 22))
        self.s1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1.setObjectName("s1")
        self.t0 = QtWidgets.QLineEdit(self.centralwidget)
        self.t0.setGeometry(QtCore.QRect(740, 170, 71, 22))
        self.t0.setInputMask("")
        self.t0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t0.setObjectName("t0")
        self.d1 = QtWidgets.QLineEdit(self.centralwidget)
        self.d1.setGeometry(QtCore.QRect(300, 170, 81, 22))
        self.d1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.d1.setObjectName("d1")
        self.f0 = QtWidgets.QLineEdit(self.centralwidget)
        self.f0.setGeometry(QtCore.QRect(210, 230, 71, 22))
        self.f0.setInputMask("")
        self.f0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f0.setObjectName("f0")
        self.w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.w2.setGeometry(QtCore.QRect(930, 260, 81, 22))
        self.w2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.w2.setObjectName("w2")
        self.x1 = QtWidgets.QLineEdit(self.centralwidget)
        self.x1.setGeometry(QtCore.QRect(830, 290, 81, 22))
        self.x1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x1.setObjectName("x1")
        self.u2 = QtWidgets.QLineEdit(self.centralwidget)
        self.u2.setGeometry(QtCore.QRect(930, 200, 81, 22))
        self.u2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.u2.setObjectName("u2")
        self.v3 = QtWidgets.QComboBox(self.centralwidget)
        self.v3.setGeometry(QtCore.QRect(550, 230, 171, 22))
        self.v3.setObjectName("v3")
        self.v3.addItem("")
        self.v3.setItemText(0, "")
        self.v3.addItem("")
        self.v3.addItem("")
        self.v3.addItem("")
        self.v3.addItem("")
        self.v3.addItem("")
        self.v3.addItem("")
        self.v3.addItem("")
        self.h1 = QtWidgets.QLineEdit(self.centralwidget)
        self.h1.setGeometry(QtCore.QRect(300, 290, 81, 22))
        self.h1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.h1.setObjectName("h1")
        self.e1 = QtWidgets.QLineEdit(self.centralwidget)
        self.e1.setGeometry(QtCore.QRect(300, 200, 81, 22))
        self.e1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e1.setObjectName("e1")
        self.e3 = QtWidgets.QComboBox(self.centralwidget)
        self.e3.setGeometry(QtCore.QRect(20, 200, 171, 22))
        self.e3.setObjectName("e3")
        self.e3.addItem("")
        self.e3.setItemText(0, "")
        self.e3.addItem("")
        self.e3.addItem("")
        self.e3.addItem("")
        self.e3.addItem("")
        self.e3.addItem("")
        self.e3.addItem("")
        self.e3.addItem("")
        self.h3 = QtWidgets.QComboBox(self.centralwidget)
        self.h3.setGeometry(QtCore.QRect(20, 290, 171, 22))
        self.h3.setObjectName("h3")
        self.h3.addItem("")
        self.h3.setItemText(0, "")
        self.h3.addItem("")
        self.h3.addItem("")
        self.h3.addItem("")
        self.h3.addItem("")
        self.h3.addItem("")
        self.h3.addItem("")
        self.h3.addItem("")
        self.x2 = QtWidgets.QLineEdit(self.centralwidget)
        self.x2.setGeometry(QtCore.QRect(930, 290, 81, 22))
        self.x2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x2.setObjectName("x2")
        self.w3 = QtWidgets.QComboBox(self.centralwidget)
        self.w3.setGeometry(QtCore.QRect(550, 260, 171, 22))
        self.w3.setObjectName("w3")
        self.w3.addItem("")
        self.w3.setItemText(0, "")
        self.w3.addItem("")
        self.w3.addItem("")
        self.w3.addItem("")
        self.w3.addItem("")
        self.w3.addItem("")
        self.w3.addItem("")
        self.w3.addItem("")
        self.f3 = QtWidgets.QComboBox(self.centralwidget)
        self.f3.setGeometry(QtCore.QRect(20, 230, 171, 22))
        self.f3.setObjectName("f3")
        self.f3.addItem("")
        self.f3.setItemText(0, "")
        self.f3.addItem("")
        self.f3.addItem("")
        self.f3.addItem("")
        self.f3.addItem("")
        self.f3.addItem("")
        self.f3.addItem("")
        self.f3.addItem("")
        self.f1 = QtWidgets.QLineEdit(self.centralwidget)
        self.f1.setGeometry(QtCore.QRect(300, 230, 81, 22))
        self.f1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1.setObjectName("f1")
        self.f2 = QtWidgets.QLineEdit(self.centralwidget)
        self.f2.setGeometry(QtCore.QRect(400, 230, 81, 22))
        self.f2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2.setObjectName("f2")
        self.h2 = QtWidgets.QLineEdit(self.centralwidget)
        self.h2.setGeometry(QtCore.QRect(400, 290, 81, 22))
        self.h2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.h2.setObjectName("h2")
        self.w0 = QtWidgets.QLineEdit(self.centralwidget)
        self.w0.setGeometry(QtCore.QRect(740, 260, 71, 22))
        self.w0.setInputMask("")
        self.w0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.w0.setObjectName("w0")
        self.e2 = QtWidgets.QLineEdit(self.centralwidget)
        self.e2.setGeometry(QtCore.QRect(400, 200, 81, 22))
        self.e2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e2.setObjectName("e2")
        self.w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.w1.setGeometry(QtCore.QRect(830, 260, 81, 22))
        self.w1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.w1.setObjectName("w1")
        self.g3 = QtWidgets.QComboBox(self.centralwidget)
        self.g3.setGeometry(QtCore.QRect(20, 260, 171, 22))
        self.g3.setObjectName("g3")
        self.g3.addItem("")
        self.g3.setItemText(0, "")
        self.g3.addItem("")
        self.g3.addItem("")
        self.g3.addItem("")
        self.g3.addItem("")
        self.g3.addItem("")
        self.g3.addItem("")
        self.g3.addItem("")
        self.v0 = QtWidgets.QLineEdit(self.centralwidget)
        self.v0.setGeometry(QtCore.QRect(740, 230, 71, 22))
        self.v0.setInputMask("")
        self.v0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v0.setObjectName("v0")
        self.g2 = QtWidgets.QLineEdit(self.centralwidget)
        self.g2.setGeometry(QtCore.QRect(400, 260, 81, 22))
        self.g2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.g2.setObjectName("g2")
        self.x0 = QtWidgets.QLineEdit(self.centralwidget)
        self.x0.setGeometry(QtCore.QRect(740, 290, 71, 22))
        self.x0.setInputMask("")
        self.x0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x0.setObjectName("x0")
        self.u0 = QtWidgets.QLineEdit(self.centralwidget)
        self.u0.setGeometry(QtCore.QRect(740, 200, 71, 22))
        self.u0.setInputMask("")
        self.u0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.u0.setObjectName("u0")
        self.v1 = QtWidgets.QLineEdit(self.centralwidget)
        self.v1.setGeometry(QtCore.QRect(830, 230, 81, 22))
        self.v1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v1.setObjectName("v1")
        self.u1 = QtWidgets.QLineEdit(self.centralwidget)
        self.u1.setGeometry(QtCore.QRect(830, 200, 81, 22))
        self.u1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.u1.setObjectName("u1")
        self.u3 = QtWidgets.QComboBox(self.centralwidget)
        self.u3.setGeometry(QtCore.QRect(550, 200, 171, 22))
        self.u3.setObjectName("u3")
        self.u3.addItem("")
        self.u3.setItemText(0, "")
        self.u3.addItem("")
        self.u3.addItem("")
        self.u3.addItem("")
        self.u3.addItem("")
        self.u3.addItem("")
        self.u3.addItem("")
        self.u3.addItem("")
        self.h0 = QtWidgets.QLineEdit(self.centralwidget)
        self.h0.setGeometry(QtCore.QRect(210, 290, 71, 22))
        self.h0.setInputMask("")
        self.h0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.h0.setObjectName("h0")
        self.g1 = QtWidgets.QLineEdit(self.centralwidget)
        self.g1.setGeometry(QtCore.QRect(300, 260, 81, 22))
        self.g1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.g1.setObjectName("g1")
        self.x3 = QtWidgets.QComboBox(self.centralwidget)
        self.x3.setGeometry(QtCore.QRect(550, 290, 171, 22))
        self.x3.setObjectName("x3")
        self.x3.addItem("")
        self.x3.setItemText(0, "")
        self.x3.addItem("")
        self.x3.addItem("")
        self.x3.addItem("")
        self.x3.addItem("")
        self.x3.addItem("")
        self.x3.addItem("")
        self.x3.addItem("")
        self.v2 = QtWidgets.QLineEdit(self.centralwidget)
        self.v2.setGeometry(QtCore.QRect(930, 230, 81, 22))
        self.v2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v2.setObjectName("v2")
        self.e0 = QtWidgets.QLineEdit(self.centralwidget)
        self.e0.setGeometry(QtCore.QRect(210, 200, 71, 22))
        self.e0.setInputMask("")
        self.e0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e0.setObjectName("e0")
        self.g0 = QtWidgets.QLineEdit(self.centralwidget)
        self.g0.setGeometry(QtCore.QRect(210, 260, 71, 22))
        self.g0.setInputMask("")
        self.g0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.g0.setObjectName("g0")
        self.o2 = QtWidgets.QLineEdit(self.centralwidget)
        self.o2.setGeometry(QtCore.QRect(400, 500, 81, 22))
        self.o2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.o2.setObjectName("o2")
        self.m2 = QtWidgets.QLineEdit(self.centralwidget)
        self.m2.setGeometry(QtCore.QRect(400, 440, 81, 22))
        self.m2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m2.setObjectName("m2")
        self.ae0 = QtWidgets.QLineEdit(self.centralwidget)
        self.ae0.setGeometry(QtCore.QRect(740, 500, 71, 22))
        self.ae0.setInputMask("")
        self.ae0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ae0.setObjectName("ae0")
        self.ac1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ac1.setGeometry(QtCore.QRect(830, 440, 81, 22))
        self.ac1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ac1.setObjectName("ac1")
        self.ad2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ad2.setGeometry(QtCore.QRect(930, 470, 81, 22))
        self.ad2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ad2.setObjectName("ad2")
        self.z0 = QtWidgets.QLineEdit(self.centralwidget)
        self.z0.setGeometry(QtCore.QRect(740, 350, 71, 22))
        self.z0.setInputMask("")
        self.z0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z0.setObjectName("z0")
        self.l3 = QtWidgets.QComboBox(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(20, 410, 171, 22))
        self.l3.setObjectName("l3")
        self.l3.addItem("")
        self.l3.setItemText(0, "")
        self.l3.addItem("")
        self.l3.addItem("")
        self.l3.addItem("")
        self.l3.addItem("")
        self.l3.addItem("")
        self.l3.addItem("")
        self.l3.addItem("")
        self.aa2 = QtWidgets.QLineEdit(self.centralwidget)
        self.aa2.setGeometry(QtCore.QRect(930, 380, 81, 22))
        self.aa2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aa2.setObjectName("aa2")
        self.ae1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ae1.setGeometry(QtCore.QRect(830, 500, 81, 22))
        self.ae1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ae1.setObjectName("ae1")
        self.ac3 = QtWidgets.QComboBox(self.centralwidget)
        self.ac3.setGeometry(QtCore.QRect(550, 440, 171, 22))
        self.ac3.setObjectName("ac3")
        self.ac3.addItem("")
        self.ac3.setItemText(0, "")
        self.ac3.addItem("")
        self.ac3.addItem("")
        self.ac3.addItem("")
        self.ac3.addItem("")
        self.ac3.addItem("")
        self.ac3.addItem("")
        self.ac3.addItem("")
        self.j1 = QtWidgets.QLineEdit(self.centralwidget)
        self.j1.setGeometry(QtCore.QRect(300, 350, 81, 22))
        self.j1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.j1.setObjectName("j1")
        self.m3 = QtWidgets.QComboBox(self.centralwidget)
        self.m3.setGeometry(QtCore.QRect(20, 440, 171, 22))
        self.m3.setObjectName("m3")
        self.m3.addItem("")
        self.m3.setItemText(0, "")
        self.m3.addItem("")
        self.m3.addItem("")
        self.m3.addItem("")
        self.m3.addItem("")
        self.m3.addItem("")
        self.m3.addItem("")
        self.m3.addItem("")
        self.y1 = QtWidgets.QLineEdit(self.centralwidget)
        self.y1.setGeometry(QtCore.QRect(830, 320, 81, 22))
        self.y1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y1.setObjectName("y1")
        self.comboBox_20 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_20.setGeometry(QtCore.QRect(550, 530, 171, 22))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.setItemText(0, "")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.aa0 = QtWidgets.QLineEdit(self.centralwidget)
        self.aa0.setGeometry(QtCore.QRect(740, 380, 71, 22))
        self.aa0.setInputMask("")
        self.aa0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aa0.setObjectName("aa0")
        self.j2 = QtWidgets.QLineEdit(self.centralwidget)
        self.j2.setGeometry(QtCore.QRect(400, 350, 81, 22))
        self.j2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.j2.setObjectName("j2")
        self.ab3 = QtWidgets.QComboBox(self.centralwidget)
        self.ab3.setGeometry(QtCore.QRect(550, 410, 171, 22))
        self.ab3.setObjectName("ab3")
        self.ab3.addItem("")
        self.ab3.setItemText(0, "")
        self.ab3.addItem("")
        self.ab3.addItem("")
        self.ab3.addItem("")
        self.ab3.addItem("")
        self.ab3.addItem("")
        self.ab3.addItem("")
        self.ab3.addItem("")
        self.ad3 = QtWidgets.QComboBox(self.centralwidget)
        self.ad3.setGeometry(QtCore.QRect(550, 470, 171, 22))
        self.ad3.setObjectName("ad3")
        self.ad3.addItem("")
        self.ad3.setItemText(0, "")
        self.ad3.addItem("")
        self.ad3.addItem("")
        self.ad3.addItem("")
        self.ad3.addItem("")
        self.ad3.addItem("")
        self.ad3.addItem("")
        self.ad3.addItem("")
        self.o0 = QtWidgets.QLineEdit(self.centralwidget)
        self.o0.setGeometry(QtCore.QRect(210, 500, 71, 22))
        self.o0.setInputMask("")
        self.o0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.o0.setObjectName("o0")
        self.l0 = QtWidgets.QLineEdit(self.centralwidget)
        self.l0.setGeometry(QtCore.QRect(210, 410, 71, 22))
        self.l0.setInputMask("")
        self.l0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l0.setObjectName("l0")
        self.i1 = QtWidgets.QLineEdit(self.centralwidget)
        self.i1.setGeometry(QtCore.QRect(300, 320, 81, 22))
        self.i1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.i1.setObjectName("i1")
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(400, 410, 81, 22))
        self.l2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l2.setObjectName("l2")
        self.o1 = QtWidgets.QLineEdit(self.centralwidget)
        self.o1.setGeometry(QtCore.QRect(300, 500, 81, 22))
        self.o1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.o1.setObjectName("o1")
        self.y3 = QtWidgets.QComboBox(self.centralwidget)
        self.y3.setGeometry(QtCore.QRect(550, 320, 171, 22))
        self.y3.setObjectName("y3")
        self.y3.addItem("")
        self.y3.setItemText(0, "")
        self.y3.addItem("")
        self.y3.addItem("")
        self.y3.addItem("")
        self.y3.addItem("")
        self.y3.addItem("")
        self.y3.addItem("")
        self.y3.addItem("")
        self.n1 = QtWidgets.QLineEdit(self.centralwidget)
        self.n1.setGeometry(QtCore.QRect(300, 470, 81, 22))
        self.n1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n1.setObjectName("n1")
        self.i0 = QtWidgets.QLineEdit(self.centralwidget)
        self.i0.setGeometry(QtCore.QRect(210, 320, 71, 22))
        self.i0.setInputMask("")
        self.i0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.i0.setObjectName("i0")
        self.ab0 = QtWidgets.QLineEdit(self.centralwidget)
        self.ab0.setGeometry(QtCore.QRect(740, 410, 71, 22))
        self.ab0.setInputMask("")
        self.ab0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ab0.setObjectName("ab0")
        self.z1 = QtWidgets.QLineEdit(self.centralwidget)
        self.z1.setGeometry(QtCore.QRect(830, 350, 81, 22))
        self.z1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z1.setObjectName("z1")
        self.ae3 = QtWidgets.QComboBox(self.centralwidget)
        self.ae3.setGeometry(QtCore.QRect(550, 500, 171, 22))
        self.ae3.setObjectName("ae3")
        self.ae3.addItem("")
        self.ae3.setItemText(0, "")
        self.ae3.addItem("")
        self.ae3.addItem("")
        self.ae3.addItem("")
        self.ae3.addItem("")
        self.ae3.addItem("")
        self.ae3.addItem("")
        self.ae3.addItem("")
        self.ad0 = QtWidgets.QLineEdit(self.centralwidget)
        self.ad0.setGeometry(QtCore.QRect(740, 470, 71, 22))
        self.ad0.setInputMask("")
        self.ad0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ad0.setObjectName("ad0")
        self.z3 = QtWidgets.QComboBox(self.centralwidget)
        self.z3.setGeometry(QtCore.QRect(550, 350, 171, 22))
        self.z3.setObjectName("z3")
        self.z3.addItem("")
        self.z3.setItemText(0, "")
        self.z3.addItem("")
        self.z3.addItem("")
        self.z3.addItem("")
        self.z3.addItem("")
        self.z3.addItem("")
        self.z3.addItem("")
        self.z3.addItem("")
        self.y2 = QtWidgets.QLineEdit(self.centralwidget)
        self.y2.setGeometry(QtCore.QRect(930, 320, 81, 22))
        self.y2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y2.setObjectName("y2")
        self.k2 = QtWidgets.QLineEdit(self.centralwidget)
        self.k2.setGeometry(QtCore.QRect(400, 380, 81, 22))
        self.k2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.k2.setObjectName("k2")
        self.y0 = QtWidgets.QLineEdit(self.centralwidget)
        self.y0.setGeometry(QtCore.QRect(740, 320, 71, 22))
        self.y0.setInputMask("")
        self.y0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y0.setObjectName("y0")
        self.p0 = QtWidgets.QLineEdit(self.centralwidget)
        self.p0.setGeometry(QtCore.QRect(210, 530, 71, 22))
        self.p0.setInputMask("")
        self.p0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p0.setObjectName("p0")
        self.k3 = QtWidgets.QComboBox(self.centralwidget)
        self.k3.setGeometry(QtCore.QRect(20, 380, 171, 22))
        self.k3.setObjectName("k3")
        self.k3.addItem("")
        self.k3.setItemText(0, "")
        self.k3.addItem("")
        self.k3.addItem("")
        self.k3.addItem("")
        self.k3.addItem("")
        self.k3.addItem("")
        self.k3.addItem("")
        self.k3.addItem("")
        self.j0 = QtWidgets.QLineEdit(self.centralwidget)
        self.j0.setGeometry(QtCore.QRect(210, 350, 71, 22))
        self.j0.setInputMask("")
        self.j0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.j0.setObjectName("j0")
        self.p3 = QtWidgets.QComboBox(self.centralwidget)
        self.p3.setGeometry(QtCore.QRect(20, 530, 171, 22))
        self.p3.setObjectName("p3")
        self.p3.addItem("")
        self.p3.setItemText(0, "")
        self.p3.addItem("")
        self.p3.addItem("")
        self.p3.addItem("")
        self.p3.addItem("")
        self.p3.addItem("")
        self.p3.addItem("")
        self.p3.addItem("")
        self.ae2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ae2.setGeometry(QtCore.QRect(930, 500, 81, 22))
        self.ae2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ae2.setObjectName("ae2")
        self.af0 = QtWidgets.QLineEdit(self.centralwidget)
        self.af0.setGeometry(QtCore.QRect(740, 530, 71, 22))
        self.af0.setInputMask("")
        self.af0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.af0.setObjectName("af0")
        self.j3 = QtWidgets.QComboBox(self.centralwidget)
        self.j3.setGeometry(QtCore.QRect(20, 350, 171, 22))
        self.j3.setObjectName("j3")
        self.j3.addItem("")
        self.j3.setItemText(0, "")
        self.j3.addItem("")
        self.j3.addItem("")
        self.j3.addItem("")
        self.j3.addItem("")
        self.j3.addItem("")
        self.j3.addItem("")
        self.j3.addItem("")
        self.z2 = QtWidgets.QLineEdit(self.centralwidget)
        self.z2.setGeometry(QtCore.QRect(930, 350, 81, 22))
        self.z2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z2.setObjectName("z2")
        self.m1 = QtWidgets.QLineEdit(self.centralwidget)
        self.m1.setGeometry(QtCore.QRect(300, 440, 81, 22))
        self.m1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m1.setObjectName("m1")
        self.ab2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ab2.setGeometry(QtCore.QRect(930, 410, 81, 22))
        self.ab2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ab2.setObjectName("ab2")
        self.aa3 = QtWidgets.QComboBox(self.centralwidget)
        self.aa3.setGeometry(QtCore.QRect(550, 380, 171, 22))
        self.aa3.setObjectName("aa3")
        self.aa3.addItem("")
        self.aa3.setItemText(0, "")
        self.aa3.addItem("")
        self.aa3.addItem("")
        self.aa3.addItem("")
        self.aa3.addItem("")
        self.aa3.addItem("")
        self.aa3.addItem("")
        self.aa3.addItem("")
        self.k0 = QtWidgets.QLineEdit(self.centralwidget)
        self.k0.setGeometry(QtCore.QRect(210, 380, 71, 22))
        self.k0.setInputMask("")
        self.k0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.k0.setObjectName("k0")
        self.ad1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ad1.setGeometry(QtCore.QRect(830, 470, 81, 22))
        self.ad1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ad1.setObjectName("ad1")
        self.af1 = QtWidgets.QLineEdit(self.centralwidget)
        self.af1.setGeometry(QtCore.QRect(830, 530, 81, 22))
        self.af1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.af1.setObjectName("af1")
        self.k1 = QtWidgets.QLineEdit(self.centralwidget)
        self.k1.setGeometry(QtCore.QRect(300, 380, 81, 22))
        self.k1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.k1.setObjectName("k1")
        self.af2 = QtWidgets.QLineEdit(self.centralwidget)
        self.af2.setGeometry(QtCore.QRect(930, 530, 81, 22))
        self.af2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.af2.setObjectName("af2")
        self.n3 = QtWidgets.QComboBox(self.centralwidget)
        self.n3.setGeometry(QtCore.QRect(20, 470, 171, 22))
        self.n3.setObjectName("n3")
        self.n3.addItem("")
        self.n3.setItemText(0, "")
        self.n3.addItem("")
        self.n3.addItem("")
        self.n3.addItem("")
        self.n3.addItem("")
        self.n3.addItem("")
        self.n3.addItem("")
        self.n3.addItem("")
        self.ac2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ac2.setGeometry(QtCore.QRect(930, 440, 81, 22))
        self.ac2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ac2.setObjectName("ac2")
        self.ac0 = QtWidgets.QLineEdit(self.centralwidget)
        self.ac0.setGeometry(QtCore.QRect(740, 440, 71, 22))
        self.ac0.setInputMask("")
        self.ac0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ac0.setObjectName("ac0")
        self.m0 = QtWidgets.QLineEdit(self.centralwidget)
        self.m0.setGeometry(QtCore.QRect(210, 440, 71, 22))
        self.m0.setInputMask("")
        self.m0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m0.setObjectName("m0")
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(300, 410, 81, 22))
        self.l1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l1.setObjectName("l1")
        self.n0 = QtWidgets.QLineEdit(self.centralwidget)
        self.n0.setGeometry(QtCore.QRect(210, 470, 71, 22))
        self.n0.setInputMask("")
        self.n0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n0.setObjectName("n0")
        self.o3 = QtWidgets.QComboBox(self.centralwidget)
        self.o3.setGeometry(QtCore.QRect(20, 500, 171, 22))
        self.o3.setObjectName("o3")
        self.o3.addItem("")
        self.o3.setItemText(0, "")
        self.o3.addItem("")
        self.o3.addItem("")
        self.o3.addItem("")
        self.o3.addItem("")
        self.o3.addItem("")
        self.o3.addItem("")
        self.o3.addItem("")
        self.i3 = QtWidgets.QComboBox(self.centralwidget)
        self.i3.setGeometry(QtCore.QRect(20, 320, 171, 22))
        self.i3.setObjectName("i3")
        self.i3.addItem("")
        self.i3.setItemText(0, "")
        self.i3.addItem("")
        self.i3.addItem("")
        self.i3.addItem("")
        self.i3.addItem("")
        self.i3.addItem("")
        self.i3.addItem("")
        self.i3.addItem("")
        self.p1 = QtWidgets.QLineEdit(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(300, 530, 81, 22))
        self.p1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p1.setObjectName("p1")
        self.n2 = QtWidgets.QLineEdit(self.centralwidget)
        self.n2.setGeometry(QtCore.QRect(400, 470, 81, 22))
        self.n2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n2.setObjectName("n2")
        self.ab1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ab1.setGeometry(QtCore.QRect(830, 410, 81, 22))
        self.ab1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ab1.setObjectName("ab1")
        self.aa1 = QtWidgets.QLineEdit(self.centralwidget)
        self.aa1.setGeometry(QtCore.QRect(830, 380, 81, 22))
        self.aa1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aa1.setObjectName("aa1")
        self.p2 = QtWidgets.QLineEdit(self.centralwidget)
        self.p2.setGeometry(QtCore.QRect(400, 530, 81, 22))
        self.p2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2.setObjectName("p2")
        self.i2 = QtWidgets.QLineEdit(self.centralwidget)
        self.i2.setGeometry(QtCore.QRect(400, 320, 81, 22))
        self.i2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.i2.setObjectName("i2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(580, 640, 51, 16))
        self.label_12.setObjectName("label_12")
        self.ctotal = QtWidgets.QLineEdit(self.centralwidget)
        self.ctotal.setGeometry(QtCore.QRect(640, 640, 113, 22))
        self.ctotal.setObjectName("ctotal")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(780, 570, 55, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_98 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_98.setGeometry(QtCore.QRect(830, 570, 121, 22))
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(980, 590, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.discount = QtWidgets.QLineEdit(self.centralwidget)
        self.discount.setGeometry(QtCore.QRect(830, 600, 121, 22))
        self.discount.setObjectName("discount")
        self.final_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.final_2.setGeometry(QtCore.QRect(830, 640, 121, 22))
        self.final_2.setObjectName("final_2")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(780, 640, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(770, 600, 55, 16))
        self.label_15.setObjectName("label_15")
        self.invalid = QtWidgets.QLabel(self.centralwidget)
        self.invalid.setGeometry(QtCore.QRect(0, 590, 401, 51))
        self.invalid.setObjectName("invalid")
        self.print = QtWidgets.QPushButton(self.centralwidget)
        self.print.setGeometry(QtCore.QRect(400, 600, 141, 41))
        self.print.setObjectName("print")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(130, 640, 141, 31))
        self.pushButton1.setObjectName("pushButton1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.clik)
        self.pushButton1.clicked.connect(self.rmvfile)
        self.print.clicked.connect(self.prnt)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DUBAI PARDHA PALACE"))
        self.label_4.setText(_translate("MainWindow", "Item"))
        self.label_5.setText(_translate("MainWindow", "Count"))
        self.label_6.setText(_translate("MainWindow", "Price"))
        self.a3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.a3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.a3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.a3.setItemText(4, _translate("MainWindow", "TOP"))
        self.a3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.a3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.a3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.a0.setText(_translate("MainWindow", "0"))
        self.a1.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Total"))
        self.a2.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Total"))
        self.label_7.setText(_translate("MainWindow", "Price"))
        self.label_8.setText(_translate("MainWindow", "Count"))
        self.label_9.setText(_translate("MainWindow", "Item"))
        self.q1.setText(_translate("MainWindow", "0"))
        self.q2.setText(_translate("MainWindow", "0"))
        self.q3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.q3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.q3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.q3.setItemText(4, _translate("MainWindow", "TOP"))
        self.q3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.q3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.q3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.q0.setText(_translate("MainWindow", "0"))
        self.b1.setText(_translate("MainWindow", "0"))
        self.r2.setText(_translate("MainWindow", "0"))
        self.b2.setText(_translate("MainWindow", "0"))
        self.r0.setText(_translate("MainWindow", "0"))
        self.r3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.r3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.r3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.r3.setItemText(4, _translate("MainWindow", "TOP"))
        self.r3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.r3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.r3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.b3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.b3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.b3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.b3.setItemText(4, _translate("MainWindow", "TOP"))
        self.b3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.b3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.b3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.r1.setText(_translate("MainWindow", "0"))
        self.c1.setText(_translate("MainWindow", "0"))
        self.d2.setText(_translate("MainWindow", "0"))
        self.d3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.d3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.d3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.d3.setItemText(4, _translate("MainWindow", "TOP"))
        self.d3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.d3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.d3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.t2.setText(_translate("MainWindow", "0"))
        self.s2.setText(_translate("MainWindow", "0"))
        self.c2.setText(_translate("MainWindow", "0"))
        self.d0.setText(_translate("MainWindow", "0"))
        self.s0.setText(_translate("MainWindow", "0"))
        self.s3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.s3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.s3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.s3.setItemText(4, _translate("MainWindow", "TOP"))
        self.s3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.s3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.s3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.t3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.t3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.t3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.t3.setItemText(4, _translate("MainWindow", "TOP"))
        self.t3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.t3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.t3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.c3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.c3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.c3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.c3.setItemText(4, _translate("MainWindow", "TOP"))
        self.c3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.c3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.c3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.c0.setText(_translate("MainWindow", "0"))
        self.t1.setText(_translate("MainWindow", "0"))
        self.s1.setText(_translate("MainWindow", "0"))
        self.t0.setText(_translate("MainWindow", "0"))
        self.d1.setText(_translate("MainWindow", "0"))
        self.f0.setText(_translate("MainWindow", "0"))
        self.w2.setText(_translate("MainWindow", "0"))
        self.x1.setText(_translate("MainWindow", "0"))
        self.u2.setText(_translate("MainWindow", "0"))
        self.v3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.v3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.v3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.v3.setItemText(4, _translate("MainWindow", "TOP"))
        self.v3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.v3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.v3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.h1.setText(_translate("MainWindow", "0"))
        self.e1.setText(_translate("MainWindow", "0"))
        self.e3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.e3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.e3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.e3.setItemText(4, _translate("MainWindow", "TOP"))
        self.e3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.e3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.e3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.h3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.h3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.h3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.h3.setItemText(4, _translate("MainWindow", "TOP"))
        self.h3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.h3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.h3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.x2.setText(_translate("MainWindow", "0"))
        self.w3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.w3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.w3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.w3.setItemText(4, _translate("MainWindow", "TOP"))
        self.w3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.w3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.w3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.f3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.f3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.f3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.f3.setItemText(4, _translate("MainWindow", "TOP"))
        self.f3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.f3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.f3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.f1.setText(_translate("MainWindow", "0"))
        self.f2.setText(_translate("MainWindow", "0"))
        self.h2.setText(_translate("MainWindow", "0"))
        self.w0.setText(_translate("MainWindow", "0"))
        self.e2.setText(_translate("MainWindow", "0"))
        self.w1.setText(_translate("MainWindow", "0"))
        self.g3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.g3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.g3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.g3.setItemText(4, _translate("MainWindow", "TOP"))
        self.g3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.g3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.g3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.v0.setText(_translate("MainWindow", "0"))
        self.g2.setText(_translate("MainWindow", "0"))
        self.x0.setText(_translate("MainWindow", "0"))
        self.u0.setText(_translate("MainWindow", "0"))
        self.v1.setText(_translate("MainWindow", "0"))
        self.u1.setText(_translate("MainWindow", "0"))
        self.u3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.u3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.u3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.u3.setItemText(4, _translate("MainWindow", "TOP"))
        self.u3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.u3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.u3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.h0.setText(_translate("MainWindow", "0"))
        self.g1.setText(_translate("MainWindow", "0"))
        self.x3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.x3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.x3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.x3.setItemText(4, _translate("MainWindow", "TOP"))
        self.x3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.x3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.x3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.v2.setText(_translate("MainWindow", "0"))
        self.e0.setText(_translate("MainWindow", "0"))
        self.g0.setText(_translate("MainWindow", "0"))
        self.o2.setText(_translate("MainWindow", "0"))
        self.m2.setText(_translate("MainWindow", "0"))
        self.ae0.setText(_translate("MainWindow", "0"))
        self.ac1.setText(_translate("MainWindow", "0"))
        self.ad2.setText(_translate("MainWindow", "0"))
        self.z0.setText(_translate("MainWindow", "0"))
        self.l3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.l3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.l3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.l3.setItemText(4, _translate("MainWindow", "TOP"))
        self.l3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.l3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.l3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.aa2.setText(_translate("MainWindow", "0"))
        self.ae1.setText(_translate("MainWindow", "0"))
        self.ac3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.ac3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.ac3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.ac3.setItemText(4, _translate("MainWindow", "TOP"))
        self.ac3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.ac3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.ac3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.j1.setText(_translate("MainWindow", "0"))
        self.m3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.m3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.m3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.m3.setItemText(4, _translate("MainWindow", "TOP"))
        self.m3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.m3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.m3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.y1.setText(_translate("MainWindow", "0"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "MAXI"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "SHALL"))
        self.comboBox_20.setItemText(4, _translate("MainWindow", "TOP"))
        self.comboBox_20.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.comboBox_20.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.comboBox_20.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.aa0.setText(_translate("MainWindow", "0"))
        self.j2.setText(_translate("MainWindow", "0"))
        self.ab3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.ab3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.ab3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.ab3.setItemText(4, _translate("MainWindow", "TOP"))
        self.ab3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.ab3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.ab3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.ad3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.ad3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.ad3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.ad3.setItemText(4, _translate("MainWindow", "TOP"))
        self.ad3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.ad3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.ad3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.o0.setText(_translate("MainWindow", "0"))
        self.l0.setText(_translate("MainWindow", "0"))
        self.i1.setText(_translate("MainWindow", "0"))
        self.l2.setText(_translate("MainWindow", "0"))
        self.o1.setText(_translate("MainWindow", "0"))
        self.y3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.y3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.y3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.y3.setItemText(4, _translate("MainWindow", "TOP"))
        self.y3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.y3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.y3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.n1.setText(_translate("MainWindow", "0"))
        self.i0.setText(_translate("MainWindow", "0"))
        self.ab0.setText(_translate("MainWindow", "0"))
        self.z1.setText(_translate("MainWindow", "0"))
        self.ae3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.ae3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.ae3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.ae3.setItemText(4, _translate("MainWindow", "TOP"))
        self.ae3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.ae3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.ae3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.ad0.setText(_translate("MainWindow", "0"))
        self.z3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.z3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.z3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.z3.setItemText(4, _translate("MainWindow", "TOP"))
        self.z3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.z3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.z3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.y2.setText(_translate("MainWindow", "0"))
        self.k2.setText(_translate("MainWindow", "0"))
        self.y0.setText(_translate("MainWindow", "0"))
        self.p0.setText(_translate("MainWindow", "0"))
        self.k3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.k3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.k3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.k3.setItemText(4, _translate("MainWindow", "TOP"))
        self.k3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.k3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.k3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.j0.setText(_translate("MainWindow", "0"))
        self.p3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.p3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.p3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.p3.setItemText(4, _translate("MainWindow", "TOP"))
        self.p3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.p3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.p3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.ae2.setText(_translate("MainWindow", "0"))
        self.af0.setText(_translate("MainWindow", "0"))
        self.j3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.j3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.j3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.j3.setItemText(4, _translate("MainWindow", "TOP"))
        self.j3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.j3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.j3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.z2.setText(_translate("MainWindow", "0"))
        self.m1.setText(_translate("MainWindow", "0"))
        self.ab2.setText(_translate("MainWindow", "0"))
        self.aa3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.aa3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.aa3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.aa3.setItemText(4, _translate("MainWindow", "TOP"))
        self.aa3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.aa3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.aa3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.k0.setText(_translate("MainWindow", "0"))
        self.ad1.setText(_translate("MainWindow", "0"))
        self.af1.setText(_translate("MainWindow", "0"))
        self.k1.setText(_translate("MainWindow", "0"))
        self.af2.setText(_translate("MainWindow", "0"))
        self.n3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.n3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.n3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.n3.setItemText(4, _translate("MainWindow", "TOP"))
        self.n3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.n3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.n3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.ac2.setText(_translate("MainWindow", "0"))
        self.ac0.setText(_translate("MainWindow", "0"))
        self.m0.setText(_translate("MainWindow", "0"))
        self.l1.setText(_translate("MainWindow", "0"))
        self.n0.setText(_translate("MainWindow", "0"))
        self.o3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.o3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.o3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.o3.setItemText(4, _translate("MainWindow", "TOP"))
        self.o3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.o3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.o3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.i3.setItemText(1, _translate("MainWindow", "MAXI"))
        self.i3.setItemText(2, _translate("MainWindow", "PARDHA"))
        self.i3.setItemText(3, _translate("MainWindow", "SHALL"))
        self.i3.setItemText(4, _translate("MainWindow", "TOP"))
        self.i3.setItemText(5, _translate("MainWindow", "LEGGINS"))
        self.i3.setItemText(6, _translate("MainWindow", "MAXI FS"))
        self.i3.setItemText(7, _translate("MainWindow", "LUNGI"))
        self.p1.setText(_translate("MainWindow", "0"))
        self.n2.setText(_translate("MainWindow", "0"))
        self.ab1.setText(_translate("MainWindow", "0"))
        self.aa1.setText(_translate("MainWindow", "0"))
        self.p2.setText(_translate("MainWindow", "0"))
        self.i2.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "Items"))
        self.label_13.setText(_translate("MainWindow", "Total"))
        self.pushButton.setText(_translate("MainWindow", "CALCULATE"))
        self.discount.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Total"))
        self.label_15.setText(_translate("MainWindow", "Discount"))
        self.invalid.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">PRINT BILL NOW</span></p></body></html>"))
        self.print.setText(_translate("MainWindow", "PRINT"))
        self.pushButton1.setText(_translate("MainWindow", "DELETE PREVIOUS BILL"))
        ki=[self.a3,self.b3,self.c3,self.d3,self.e3,self.f3,self.g3,self.h3,self.i3,self.j3,self.k3,self.l3,self.m3,self.n3,self.o3,self.p3,self.q3,self.r3,self.s3,self.t3,self.u3,self.v3,self.w3,self.x3,self.y3,self.z3,self.aa3,self.ab3,self.ac3,self.ad3,self.ae3,self.comboBox_20]

        for i in ki:
            i.addItem("SHIRT")

    def rmvfile(self):
        try:
            dati=date.today()
            fold=str(dati).split('-')
            fold.reverse()
            fold=''.join(fold)
            a=os.listdir(fold)
            a=list(map(lambda x:int(x[6:-4]),a))
            p=fold+'\\'+"DUBAI "+str(max(a))+".txt"
            os.remove(p)
            self.invalid.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">FILE REMOVED</span></p></body></html>")
            print("removed file "+p)
        except:
            self.invalid.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">NO FILE TO DELETE</span></p></body></html>")
            
                
    def clik(self):
        x=[self.a0,self.b0,self.c0,self.d0,self.e0,self.f0,self.g0,self.h0,self.i0,self.j0,self.k0,self.l0,self.m0,self.n0,self.o0,self.p0,self.q0,self.r0,self.s0,self.t0,self.u0,self.v0,self.w0,self.x0,self.y0,self.z0,self.aa0,self.ab0,self.ac0,self.ad0,self.ae0,self.af0]
        y=[self.a1,self.b1,self.c1,self.d1,self.e1,self.f1,self.g1,self.h1,self.i1,self.j1,self.k1,self.l1,self.m1,self.n1,self.o1,self.p1,self.q1,self.r1,self.s1,self.t1,self.u1,self.v1,self.w1,self.x1,self.y1,self.z1,self.aa1,self.ab1,self.ac1,self.ad1,self.ae1,self.af1]
        z=[self.a2,self.b2,self.c2,self.d2,self.e2,self.f2,self.g2,self.h2,self.i2,self.j2,self.k2,self.l2,self.m2,self.n2,self.o2,self.p2,self.q2,self.r2,self.s2,self.t2,self.u2,self.v2,self.w2,self.x2,self.y2,self.z2,self.aa2,self.ab2,self.ac2,self.ad2,self.ae2,self.af2]
        ki=[self.a3,self.b3,self.c3,self.d3,self.e3,self.f3,self.g3,self.h3,self.i3,self.j3,self.k3,self.l3,self.m3,self.n3,self.o3,self.p3,self.q3,self.r3,self.s3,self.t3,self.u3,self.v3,self.w3,self.x3,self.y3,self.z3,self.aa3,self.ab3,self.ac3,self.ad3,self.ae3,self.comboBox_20]
        try:
            self.pushButton.setText('CALCULATE')
            total=0
            count=0
            for i in range(len(x)):
                z[i].setText(str(int(x[i].text())*int(y[i].text())))
                total+=int(x[i].text())*int(y[i].text())
                count+=int(x[i].text())
            self.lineEdit_98.setText(str(total))
            self.ctotal.setText(str(count))
            k=self.discount.text()
            if k[-1]=='%':
                ftotal=((100-float(k[:len(k)-1]))/100)*float(self.lineEdit_98.text())
            else:
                ftotal=float(self.lineEdit_98.text())-float(k)
            ftotal=round(ftotal,4)
            self.final_2.setText(str(ftotal))

        except:
            self.invalid.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">INVALID, CHECK COUNT , PRICE & TRY AGAIN</span></p></body></html>")
        
    def prnt(self):
            x=[self.a0,self.b0,self.c0,self.d0,self.e0,self.f0,self.g0,self.h0,self.i0,self.j0,self.k0,self.l0,self.m0,self.n0,self.o0,self.p0,self.q0,self.r0,self.s0,self.t0,self.u0,self.v0,self.w0,self.x0,self.y0,self.z0,self.aa0,self.ab0,self.ac0,self.ad0,self.ae0,self.af0]
            y=[self.a1,self.b1,self.c1,self.d1,self.e1,self.f1,self.g1,self.h1,self.i1,self.j1,self.k1,self.l1,self.m1,self.n1,self.o1,self.p1,self.q1,self.r1,self.s1,self.t1,self.u1,self.v1,self.w1,self.x1,self.y1,self.z1,self.aa1,self.ab1,self.ac1,self.ad1,self.ae1,self.af1]
            z=[self.a2,self.b2,self.c2,self.d2,self.e2,self.f2,self.g2,self.h2,self.i2,self.j2,self.k2,self.l2,self.m2,self.n2,self.o2,self.p2,self.q2,self.r2,self.s2,self.t2,self.u2,self.v2,self.w2,self.x2,self.y2,self.z2,self.aa2,self.ab2,self.ac2,self.ad2,self.ae2,self.af2]
            ki=[self.a3,self.b3,self.c3,self.d3,self.e3,self.f3,self.g3,self.h3,self.i3,self.j3,self.k3,self.l3,self.m3,self.n3,self.o3,self.p3,self.q3,self.r3,self.s3,self.t3,self.u3,self.v3,self.w3,self.x3,self.y3,self.z3,self.aa3,self.ab3,self.ac3,self.ad3,self.ae3,self.comboBox_20]  
            dati=date.today()
            dat=str(dati).split('-')

            dat.reverse()
            dat=''.join(dat)
            k=(time.ctime().split())
            tm=''.join(k[3].split(':'))
            filecode='DUBAI '+dat+tm
            filename='DUBAI '+dat+tm+'.txt'
            if not os.path.exists(dat):
                os.mkdir(dat)
            path=dat+str("\\")+ filename
            f=open(path,'w')
            lin1="DUBAI PARDHA PALACE".center(85)+'\n'
            contact="Melechelari".center(42)+"Phone:9999999999".center(43)+'\n'
            lin2=(("Date: "+str(dati)+"  Time: "+k[3]).ljust(43)+ ("Billno: "+filecode).rjust(42)+'\n')
            lin3="Item".center(22)+"Count".center(23)+"Price".center(21)+"Total".center(23)+"\n"
            L=['-'*85+'\n',lin1,contact,'-'*85+'\n',lin2,'-'*85+'\n',lin3,'-'*85+'\n']
            for i in range(len(x)):
                if ki[i].currentText():
                    data=ki[i].currentText().ljust(22)+'|'+x[i].text().center(21)+'|'+y[i].text().center(21)+'|'+z[i].text().center(21)+"\n"
                    L.append(data)

            L.append('\n')
            L.append('-'*85+'\n')
            data=('items: '+self.ctotal.text()+'   price: '+self.lineEdit_98.text()).rjust(85)
            L.append(data+'\n')
            L.append(('Discount/Return: '+self.discount.text()).rjust(85)+'\n')
            L.append(('Total: '+self.final_2.text()).rjust(85)+'\n')
            L.append(('THANKS FOR SHOPPING'.center(85,'-')))
                
            f.writelines(L)
            f.close()
            pri="start notepad.exe "+path
            os.system(pri)
            self.invalid.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">BILL ADDED</span></p></body></html>")
            print("bill saved in "+path)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
